apiVersion: v1
kind: Service
metadata:
  name: {{ include "psql-master.fullname" . }}
  labels:
    {{- include "psql-master.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
      name: http
  selector:
    {{- include "psql-master.selectorLabels" . | nindent 4 }}
