apiVersion: v1
kind: PersistentVolume
metadata:
  name: porstgresql-slave
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/postgresql/slave
